services:
  spot-lsm:
    image: test:latest
    container_name: container-spot-lsm
    environment:
      - TZ=America/Chicago
    
    volumes:
      - /home/lpham/CODE/SPOT-LSM-survey:/home/SPOT-LSM-survey
      #mounting usb bus for the digitizer
      - /run/udev:/run/udev:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0:/dev/ttyACM0
      #time zone 
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    privileged: true
    # command: ["${spot_host}"]
    #uncomment two lines below to exec into the containe for debugging
    entrypoint: [ "/bin/bash", "-c" ]
    command: [ "while true; do sleep 30; done;" ]
    
