services:
  spot-lsm:
    image: spot-mirion
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    container_name: container-spot-lsm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/lpham/CODE/SPOT-LSM-survey/src/data_acquisitions/data:/SPOT-LSM-survey/src/data_acquisitions/data
      - /run/udev:/run/udev:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    privileged: true
   
  drain-history:
    image: spot-drain-history
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile2
    container_name: drain-history-container
    volumes:
      - /home/lpham/CODE/SPOT-LSM-survey/src/data_acquisitions/data:/SPOT-LSM-survey/src/data_acquisitions/data
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
    
